[platformio]
extra_configs =
    settings.ini
default_envs = d1_mini
lib_dir = .
src_dir = examples/ESP8266
;src_dir = examples/ESP32

[env]
framework = arduino
build_flags = 
    ${settings.build_flags}
    ; -D ASYNC_TCP_SSL_IN_BUFFER_SIZE=1024
    ; -D ASYNC_TCP_SSL_OUT_BUFFER_SIZE=1024
    ; -D DEBUG_ESP_PORT=Serial
    ; -D ASYNC_TCP_SSL_ENABLED=1
    ; -D DEBUG_ESP_ASYNC_TCP=1
    ; -D DEBUG_ESP_TCP_SSL=1 

monitor_speed = 115200
monitor_parity = N
monitor_dtr = 1

[env:d1_mini]
platform = espressif8266
board = d1_mini
build_flags = 
    ${env.build_flags}
    -D ASYNC_TCP_SSL_ENABLED=1
lib_deps = 
  https://github.com/abratchik/ESPAsyncTCP

